name: pytest-unit-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  miniconda:
    name: Miniconda (${{ matrix.os }}, python${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: ['3.6', '3.11']

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
    - name: Set up Python ${{ matrix.python-version }}
      with:
          activate-environment: ${{ matrix.os }}-${{ matrix.python-version }}
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        pytest tests/
