name: pytest-conda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  conda:
    name: conda
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Create conda environment
      run: |
        conda env create -f environment.yml -q

    - name: Test with pytest
      run: |
        exec bash
        conda init bash
        conda activate ci
        pip install .
        pytest tests/
