name: pytest-conda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  conda:
    name: conda
    runs-on: ubuntu-latest

    steps:
    - name: Create conda environment
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          pip install .

    - name: Create conda environment
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env create -f environment.yml -q

    - name: Test with pytest
      run: |
        $CONDA/bin/conda activate ci
        pip install .
        $CONDA/bin/pytest tests/
