name: pytest-conda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  create-env:
    name: conda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          # mamba-version: "*"
          channels: defaults, conda-forge
          auto-activate-base: false
          activate-environment: ci
          environment-file: environment.yml
      
      - name: Test with pytest
        run: |
          pip install .
          pytest tests/
