name: update-doc

on:
    push:
      branches:
        - master

jobs:
  doc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
        pip install --upgrade pip
        pip install sphinx
    
    - name: Generate the latest version documentation
      run: |
        sphinx-build -b latex docs .
        pdflatex ci_mpm.tex -output-directory=docs
    
    - name: commit
      run: |
        git config --global user.email jingyang.min22@imperial.ac.uk
        git config --global user.name acse-cd1f515d
        git add .
        git commit -a -m 'update doc'

    - name: Push the latest version documentation
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
